// genreOptions.js;
const genreOptions = [
  { value: 1, label: "Action" },
  { value: 2, label: "Adventure" },
  { value: 3, label: "Racing" },
  { value: 4, label: "Comedy" },
  { value: 5, label: "Avant Garde" },
  { value: 6, label: "Mythology" },
  { value: 7, label: "Mystery" },
  { value: 8, label: "Drama" },
  { value: 9, label: "Ecchi" },
  { value: 10, label: "Fantasy" },
  { value: 11, label: "Strategy" },
  { value: 12, label: "Hentai" },
  { value: 13, label: "Historical" },
  { value: 14, label: "Horror" },
  { value: 15, label: "Kids" },
  { value: 17, label: "Martial Arts" },
  { value: 18, label: "Mecha" },
  { value: 19, label: "Music" },
  { value: 20, label: "Parody" },
  { value: 21, label: "Samurai" },
  { value: 22, label: "Romance" },
  { value: 23, label: "School" },
  { value: 24, label: "Sci-Fi" },
  { value: 25, label: "Shoujo" },
  { value: 26, label: "Girls Love" },
  { value: 27, label: "Shounen" },
  { value: 28, label: "Boys Love" },
  { value: 29, label: "Space" },
  { value: 30, label: "Sports" },
  { value: 31, label: "Super Power" },
  { value: 32, label: "Vampire" },
  { value: 35, label: "Harem" },
  { value: 36, label: "Slice of Life" },
  { value: 37, label: "Supernatural" },
  { value: 38, label: "Military" },
  { value: 39, label: "Detective" },
  { value: 40, label: "Psychological" },
  { value: 41, label: "Suspense" },
  { value: 42, label: "Seinen" },
  { value: 43, label: "Josei" },
  { value: 46, label: "Award Winning" },
  { value: 47, label: "Gourmet" },
  { value: 48, label: "Workplace" },
  { value: 49, label: "Erotica" },
  { value: 50, label: "Adult Cast" },
  { value: 51, label: "Anthropomorphic" },
  { value: 52, label: "CGDCT" },
  { value: 53, label: "Childcare" },
  { value: 54, label: "Combat Sports" },
  { value: 55, label: "Delinquents" },
  { value: 56, label: "Educational" },
  { value: 57, label: "Gag Humor" },
  { value: 58, label: "Gore" },
  { value: 59, label: "High Stakes Game" },
  { value: 60, label: "Idols (Female)" },
  { value: 61, label: "Idols (Male)" },
  { value: 62, label: "Isekai" },
  { value: 63, label: "Iyashikei" },
  { value: 64, label: "Love Polygon" },
  { value: 65, label: "Magical Sex Shift" },
  { value: 66, label: "Mahou Shoujo" },
  { value: 67, label: "Medical" },
  { value: 68, label: "Organized Crime" },
  { value: 69, label: "Otaku Culture" },
  { value: 70, label: "Performing Arts" },
  { value: 71, label: "Pets" },
  { value: 72, label: "Reincarnation" },
  { value: 73, label: "Reverse Harem" },
  { value: 74, label: "Romantic Subtext" },
  { value: 75, label: "Showbiz" },
  { value: 76, label: "Survival" },
  { value: 77, label: "Team Sports" },
  { value: 78, label: "Time Travel" },
  { value: 79, label: "Video Game" },
  { value: 80, label: "Visual Arts" },
  { value: 81, label: "Crossdressing" },
];

export default genreOptions;
